### ISSUE TITLE
Quoting vars in Lucius breaks syntax highlighting

### ISSUE THREAD

**Issue by AKurilin** [pbrisbin/vim-syntax-shakespeare#18]
Creating the issue mostly for tracking purposes.

```
span.something_else { font: "#{myFont}" }
```

In the line above the none of the curly braces are matched correctly and the first quote doesn't seem to be closed at all, meaning that the rest of the file after it is highlighted as continuation of that string.

Doesn't look like Cassius is affected by this at all.

**Comment by pbrisbin** [comment]
I added this example to `test.lucius` and it seems to highlight correctly. This may have been a `css.vim` issue that's been fixed.
