### ISSUE TITLE
Highlight .hamlet on newlines inside tags breaks *during editing*

### ISSUE THREAD

**Issue by wolftune** [pbrisbin/vim-syntax-shakespeare#23]
I do have some other plugins, so it is _possible_ there's an interaction, but I see that you fixed #13 and thanks for that.

In my situation, any _editing_ of multiline tags in .hamlet breaks the syntax highlighting until the file is reloaded. So, in a situation like:

```
      <input 
        type="submit"
        name="mode"
        value="preview">
```

The highlighting works at first opening. Edit at all in the lower three lines, all three of them immediately lose their highlighting.

**Comment by pbrisbin** [comment]
That fact that it works, then doesn't makes me suspect it's some other setting. Can you please make a minimal vimrc to reproduce with `vim -u minimal.vim`? Something like:

```vim
set nocompatible

filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Plugin 'gmarik/vundle'
Plugin 'pbrisbin/vim-syntax-shakespeare'

syntax on
filetype plugin indent on
```

**Comment by wolftune** [comment]
Ok, done, tested with absolutely nothing except that minimal thing (had to change /bundle/vundle/ to /bundle/Vundle.vim). I had no other plugins at all. Reproduced the very same issue. It is not an interaction with other plugins.

**Comment by pbrisbin** [comment]
Cool. I might have time to look into this on Friday

**Comment by wolftune** [comment]
it seems the syntax engages correctly on a number of triggers…

* if I highlight any pair of a brace or paren anywhere in the file, it updates the syntax and I get it back.
* if I move a single item back to the original line, it all comes back, even if some are still on new-lines.
* I can add a newline and not break it, but it breaks if I edit anything that is on the new line.
* when it breaks, it only breaks for the line I'm on and those below, but not for those above the line I'm editing.

P.S. Thanks for the wonderful plugin overall!

**Comment by pbrisbin** [comment]
I'm still not sure what this is or if I'll be able to fix, but I'd like to offer a workaround I use whenever syntax "goes funny" for me: `<C-l>` is a pretty common "clear screen" binding in most Linux applications and for vim it forces a re-draw and can often clear up highlighting issues.

**Comment by wolftune** [comment]
Thanks for the other updates too, the Ctrl-L workaround is good!

**Comment by pbrisbin** [comment]
@wolftune can you confirm if this is still an issue in latest vim? I'd like to close it as stale.

**Comment by wolftune** [comment]
From a quick trial, I'm not reproducing the issue! I'm not on latest vim, but I'm on the latest that's in Ubuntu 16.04. Anyway, I'll close. Ignore unless it's experienced again. Cheers
