### ISSUE TITLE
some highlighting for non-quoted .hamlet syntax

### ISSUE THREAD

**Issue by wolftune** [pbrisbin/vim-syntax-shakespeare#24]
So `type=submit` is valid and the same as `type="submit"`

It would be nice to somehow recognize the former for syntax highlighting of some sort. My understanding is that the quotes are needed for anything that contains spaces but otherwise not needed.

**Comment by pbrisbin** [comment]
I might have time to look into this Friday. Looks like changing `hmAttr` to allow spaces if quoted is what's needd.

**Comment by wolftune** [comment]
I don't know really, but I don't think there's a problem with allowing spaces if quoted. Everything works perfectly *when* quoted. What I want is to recognize and highlight `submit` within `type=submit` even when it *isn't* quoted. So, it probably needs just a highlighting of the first word following an `=` *if* it is not something that gets highlighting otherwise such as `"` or `@{…` and so on.
