### ISSUE TITLE
Missing screenshot Readme.md

### ISSUE THREAD

**Issue by stefan-j** [pbrisbin/vim-syntax-shakespeare#29]
Screenshot image is missing in readme.md

**Comment by pbrisbin** [comment]
Thanks for reporting this. I'm tempted to say it's a GitHub CDN issue. The source in the README does point to a URL that exists:

https://files.pbrisbin.com/screenshots/desktop_1202101148.png

I'll see if maybe a local screenshot file works better?

**Comment by pbrisbin** [comment]
Seems to have worked.
